import { useMemo, useState } from 'react';
import { CheckCircle2, Clock3, GraduationCap, HeartHandshake, Loader2, Send, ShieldCheck, UserRoundCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';

const statusLabels = { pendiente: 'En revisión', aprobada: 'Aprobada', rechazada: 'No aprobada', cancelada: 'Cancelada' };
const statusStyles = { pendiente: 'bg-amber-100 text-amber-900', aprobada: 'bg-emerald-100 text-emerald-900', rechazada: 'bg-rose-100 text-rose-900', cancelada: 'bg-slate-100 text-slate-700' };

export default function VoluntariadoPortal() {
  const { currentUser, voluntariosList = [], postulacionesVoluntariadoList = [], solicitarIngresoSocioDesdeVoluntariado } = useAuth();
  const [motivacion, setMotivacion] = useState('');
  const [antecedentes, setAntecedentes] = useState('');
  const [requestState, setRequestState] = useState({ status: 'idle', message: '' });
  const volunteer = voluntariosList.find((item) => item.email?.toLowerCase() === currentUser?.email?.toLowerCase());
  const myRequests = useMemo(() => postulacionesVoluntariadoList.filter((item) => item.email?.toLowerCase() === currentUser?.email?.toLowerCase() || item.voluntarioId === volunteer?.id), [postulacionesVoluntariadoList, currentUser?.email, volunteer?.id]);
  const membershipRequest = myRequests.find((item) => item.tipo === 'ascenso_socio' && item.estado === 'pendiente');

  const submitMembership = async (event) => {
    event.preventDefault();
    setRequestState({ status: 'loading', message: '' });
    const result = await solicitarIngresoSocioDesdeVoluntariado({ motivacion, antecedentes });
    if (result?.ok) { setRequestState({ status: 'success', message: 'Tu solicitud fue enviada al Directorio para su revisión.' }); setMotivacion(''); setAntecedentes(''); return; }
    setRequestState({ status: 'error', message: result?.error?.message || 'No pudimos registrar la solicitud. Inténtalo nuevamente.' });
  };

  return <section className="space-y-7 font-['Plus_Jakarta_Sans'] text-slate-900">
    <header className="relative overflow-hidden rounded-3xl bg-slate-950 p-6 text-white shadow-xl sm:p-9"><div className="absolute -right-16 -top-16 h-56 w-56 rounded-full bg-emerald-500/20 blur-3xl" /><div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-bold uppercase tracking-wider text-emerald-300"><HeartHandshake className="h-4 w-4" aria-hidden="true" /> Espacio de voluntariado</span><h2 className="mt-4 font-['Outfit'] text-3xl font-extrabold tracking-tight sm:text-4xl">Hola, {currentUser?.name?.split(' ')[0] || 'voluntario/a'}.</h2><p className="mt-3 text-sm leading-6 text-slate-300">Aquí encontrarás tu estado, acceso a formación y las gestiones de tu participación en PRUANED.</p></div></header>
    {volunteer ? <div className="grid gap-4 md:grid-cols-3"><Info icon={UserRoundCheck} label="Estado de incorporación" value={volunteer.estado === 'inactivo' ? 'Inactivo' : 'Voluntario/a activo/a'} tone={volunteer.estado === 'inactivo' ? 'slate' : 'emerald'} /><Info icon={GraduationCap} label="Acreditación" value={volunteer.nivelAcreditacion || 'En proceso'} /><Info icon={Clock3} label="Disponibilidad" value={volunteer.disponibilidadRespuesta || 'Por actualizar'} /></div> : <div role="status" className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><Clock3 className="mt-0.5 h-5 w-5 flex-none text-amber-700" aria-hidden="true" /><p>Tu incorporación aún está en revisión. Cuando sea aprobada, se habilitarán tus datos de voluntariado y el aula virtual.</p></div>}
    <div className="grid gap-6 lg:grid-cols-[1.05fr_0.95fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-100 text-emerald-700"><GraduationCap className="h-5 w-5" aria-hidden="true" /></span><div><h3 className="font-['Outfit'] text-xl font-extrabold">Aula virtual</h3><p className="mt-1 text-sm leading-6 text-slate-600">Revisa contenidos, completa módulos y mantén tus conocimientos preparados para apoyar.</p></div></div><Link to="/intranet/voluntarios/aula" className="mt-6 inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-emerald-700 px-4 text-sm font-bold text-white transition hover:bg-emerald-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700">Ir al aula virtual</Link></article>
      <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 flex-none text-emerald-700" aria-hidden="true" /><div><h3 className="font-['Outfit'] text-xl font-extrabold">Tu participación protegida</h3><p className="mt-1 text-sm leading-6 text-slate-600">La coordinación utiliza tus datos de disponibilidad sólo para organizar actividades y emergencias.</p></div></div><p className="mt-5 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600">Mantén actualizados tus datos de contacto y recursos cuando la coordinación lo solicite.</p></article></div>
    <section aria-labelledby="requests-title" className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700">Seguimiento</p><h3 id="requests-title" className="mt-1 font-['Outfit'] text-xl font-extrabold">Mis solicitudes</h3></div></div>{myRequests.length ? <div className="mt-5 divide-y divide-slate-100">{myRequests.map((request) => <div key={request.id} className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-slate-900">{request.tipo === 'ascenso_socio' ? 'Solicitud para ser socio/a' : request.tipo === 'derivada_socio' ? 'Incorporación derivada de postulación a socio' : 'Postulación de voluntariado'}</p><p className="mt-1 text-xs text-slate-500">Enviada {request.createdAt ? new Date(request.createdAt).toLocaleDateString('es-CL') : 'recientemente'}{request.observacionRevision ? ` · ${request.observacionRevision}` : ''}</p></div><span className={`inline-flex w-fit rounded-full px-3 py-1 text-xs font-bold ${statusStyles[request.estado] || statusStyles.pendiente}`}>{statusLabels[request.estado] || request.estado}</span></div>)}</div> : <p className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm text-slate-600">No hay solicitudes registradas para esta cuenta.</p>}</section>
    {volunteer && <section aria-labelledby="membership-title" className="rounded-3xl border border-blue-100 bg-blue-50/60 p-6"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-700">Trayectoria</p><h3 id="membership-title" className="mt-1 font-['Outfit'] text-xl font-extrabold">¿Quieres postular para ser socio/a?</h3><p className="mt-2 text-sm leading-6 text-slate-700">Tu experiencia como voluntario/a puede respaldar una postulación. La decisión siempre requiere aprobación del Directorio; seguirás siendo voluntario/a durante la revisión.</p></div>{membershipRequest ? <p role="status" className="mt-5 inline-flex items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-bold text-amber-900"><Clock3 className="h-4 w-4" aria-hidden="true" />Ya tienes una solicitud en revisión.</p> : <form onSubmit={submitMembership} className="mt-5 grid gap-4 lg:grid-cols-2"><label className="text-sm font-bold text-slate-800">Motivación<textarea required value={motivacion} onChange={(event) => setMotivacion(event.target.value)} rows="4" className="mt-1.5 w-full rounded-xl border border-blue-200 bg-white p-3 text-sm font-normal text-slate-900 focus:border-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-100" /></label><label className="text-sm font-bold text-slate-800">Antecedentes relevantes <span className="font-normal text-slate-500">(opcional)</span><textarea value={antecedentes} onChange={(event) => setAntecedentes(event.target.value)} rows="4" className="mt-1.5 w-full rounded-xl border border-blue-200 bg-white p-3 text-sm font-normal text-slate-900 focus:border-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-100" /></label><div className="lg:col-span-2">{requestState.status !== 'idle' && <p role={requestState.status === 'error' ? 'alert' : 'status'} className={`mb-3 rounded-xl p-3 text-sm font-semibold ${requestState.status === 'error' ? 'bg-rose-50 text-rose-800' : 'bg-emerald-50 text-emerald-800'}`}>{requestState.message}</p>}<button type="submit" disabled={requestState.status === 'loading'} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-blue-700 px-5 text-sm font-extrabold text-white transition hover:bg-blue-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-700 disabled:cursor-wait disabled:opacity-70">{requestState.status === 'loading' ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" /> : <Send className="h-4 w-4" aria-hidden="true" />}{requestState.status === 'loading' ? 'Enviando…' : 'Solicitar evaluación del Directorio'}</button></div></form>}</section>}
  </section>;
}

function Info({ icon: Icon, label, value, tone = 'blue' }) { const colors = tone === 'emerald' ? 'bg-emerald-100 text-emerald-700' : 'bg-blue-100 text-blue-700'; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className={`h-5 w-5 ${colors.split(' ')[1]}`} aria-hidden="true" /><p className="mt-3 text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 font-['Outfit'] text-lg font-extrabold text-slate-950">{value}</p></article>; }
